# OpenCode QA Skill Installer for Windows
# This script is dynamically generated by the server, SERVER_URL has been replaced

param(
    [Parameter(Mandatory=$true, Position=0)]
    [string]$Slug,
    [switch]$Force,
    [string]$Source,
    [string]$TargetDir
)

$ErrorActionPreference = "Stop"

$ServerUrl = "{{SERVER_URL}}"

if ($TargetDir) {
    $InstallDir = Join-Path $TargetDir $Slug
} else {
    $InstallDir = Join-Path $env:USERPROFILE ".opencode\skills\$Slug"
}

Write-Host "Installing skill: $Slug"
Write-Host "Server: $ServerUrl"
Write-Host "Target: $InstallDir"
Write-Host ""

if (Test-Path $InstallDir) {
    if ($Force) {
        Write-Host "Overwriting existing installation..."
        Remove-Item -Recurse -Force $InstallDir
    } else {
        Write-Host "Directory already exists: $InstallDir"
        $response = Read-Host "Overwrite? [y/N]"
        if ($response -ne 'y' -and $response -ne 'Y') {
            Write-Host "Cancelled"
            exit 0
        }
        Remove-Item -Recurse -Force $InstallDir
    }
}

$TempDir = Join-Path $env:TEMP "opencode-skill-$(Get-Random)"
New-Item -ItemType Directory -Force -Path $TempDir | Out-Null

try {
    $ZipFile = Join-Path $TempDir "$Slug.zip"
    $DownloadUrl = "$ServerUrl/api/public/skills/$Slug/download"
    if ($Source) {
        $DownloadUrl = "$DownloadUrl`?source=$Source"
    }
    
    Write-Host "Downloading: $DownloadUrl"
    
    try {
        Invoke-WebRequest -Uri $DownloadUrl -OutFile $ZipFile -UseBasicParsing
    } catch {
        Write-Host "Error: Download failed - $_"
        exit 1
    }
    
    if (-not (Test-Path $ZipFile) -or (Get-Item $ZipFile).Length -eq 0) {
        Write-Host "Error: Downloaded file is empty"
        exit 1
    }
    
    New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
    
    try {
        Expand-Archive -Path $ZipFile -DestinationPath $InstallDir -Force
    } catch {
        Write-Host "Error: Failed to extract zip file - $_"
        Remove-Item -Recurse -Force $InstallDir -ErrorAction SilentlyContinue
        exit 1
    }
    
    Write-Host ""
    Write-Host "============================================"
    Write-Host "Installation complete!"
    Write-Host "Skill installed to: $InstallDir"
    Write-Host "============================================"
} finally {
    Remove-Item -Recurse -Force $TempDir -ErrorAction SilentlyContinue
}
